### ISSUE TITLE
Model_data function not working

### ISSUE THREAD

**Issue by cojocarucosmin** [mifek/bmarketing#10]
Function model_data uses rpart library which is not stated in documentation as a dependency to be installed.
Even after installing rpart, the function doesn't work on bmarketing2.csv dataset:
![image](https://user-images.githubusercontent.com/45625860/57439260-4b6d9880-724e-11e9-8a86-8ce2d04c0fe5.png)

**Comment by mifek** [comment]
#8 fixed
