### ISSUE TITLE
Warning when calling plot_model

### ISSUE THREAD

**Issue by apeterseil** [mifek/bmarketing#12]
When calling the plot_model a warning appears.  Can make the user think that something does not work properly.

Warning message:
Cannot retrieve the data used to build the model (so cannot determine roundint and is.binary for the variables).
To silence this warning:
    Call rpart.plot with roundint=FALSE,
    or rebuild the rpart model with model=TRUE.

**Comment by mifek** [comment]
setting model = TRUE helped
