### ISSUE TITLE
clean_data should have a data.frame as input

### ISSUE THREAD

**Issue by apeterseil** [mifek/bmarketing#14]
The process of reading in data and cleaning it should be separated. The input of the clean_data function should be a data.frame. E.g. In case the read in data.frame contains NAs in the target variable its hard to change this in R and clean it again.

--> So a data.frame as input parameter and no reading in the clean_data function.

**Comment by mifek** [comment]
Fixed by https://github.com/mifek/bmarketing/commit/ef172ef26d4aa965ce7f178323b11c033b4ac692
