### ISSUE TITLE
Clean data function - It is not clear which aruments are needed

### ISSUE THREAD

**Issue by pmaletic** [mifek/bmarketing#2]
Clean data function as a first argument takes path of the file instead of dataframe which is misleading a bit.

Also it keeps throwing error when new data set with different CSV separator is in place (arguments to read_csv are not working)

**Comment by cojocarucosmin** [comment]
na_threshold argument is not clear what it is referring to and what needs to be sent here

**Comment by mifek** [comment]
changed to ,-styled cdv files
added documentation on threshold

**Comment by mifek** [comment]
closed
