### ISSUE TITLE
transform_data not working

### ISSUE THREAD

**Issue by apeterseil** [mifek/bmarketing#4]
After loading the package the command 

transform_data(data2,cols = c("BALANCE","DURATION"))

with the dataset data2 is not working. I am getting the error

Error in mutate_if(df, is.factor, readr::parse_double) %>% mutate_at(cols,  : 
  could not find function "%>%"

After loading tidyverse this disappears. It is better to make the package load its dependencies automatically.

**Comment by mifek** [comment]
added dependency
